<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPHSpOO1\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPHSpOO1/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPHSpOO1.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPHSpOO1\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerPHSpOO1\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'PHSpOO1',
    'container.build_id' => 'fba5bd53',
    'container.build_time' => 1523208503,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPHSpOO1');
